name: tharad_tech
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: null
  flutter_svg: null
  cached_network_image:
  dotted_border:
  dio:
  fluttertoast:
  flutter_bloc:
  get_storage:
  easy_localization:
  image_picker:
  pin_code_fields:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal_regular.ttf
    - family: Alexandria
      fonts:
        - asset: assets/fonts/alexandria_regular.ttf
